### ISSUE TITLE
Add congressional district

### ISSUE THREAD

**Issue by lkwhite** [jayhesselberth/nihexporter#23]
Include ORG_DISTRICT in raw projects data for better geographic filtering options for funding advocacy.

**Comment by jayhesselberth** [comment]
This information would end up in the `org_info` table. What types of values does the ORG_DISTRICT column take?

**Comment by lkwhite** [comment]
Integers between 1 and 49, plus the number 98 which is a special congressional district code for Washington, D.C. (Everything else including Puerto Rico will return an NA.) All tibbles that contain ORG_DISTRICT would need to also contain the state so that you could output something meaningful, like the total value of all NIH grants awarded in 2016 to grantees in Colorado CD6.
